/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUnmatchedQuestionsRouteImport } from './routes/_admin.unmatched-questions'
import { Route as AdminThemeSettingsRouteImport } from './routes/_admin.theme-settings'
import { Route as AdminSiteContentRouteImport } from './routes/_admin.site-content'
import { Route as AdminSecurityPermissionsRouteImport } from './routes/_admin.security-permissions'
import { Route as AdminPromptHistoryRouteImport } from './routes/_admin.prompt-history'
import { Route as AdminPlatformTransferRouteImport } from './routes/_admin.platform-transfer'
import { Route as AdminPlatformControlCenterRouteImport } from './routes/_admin.platform-control-center'
import { Route as AdminLocaleStudioRouteImport } from './routes/_admin.locale-studio'
import { Route as AdminHelpCardsRouteImport } from './routes/_admin.help-cards'
import { Route as AdminGuideImagesRouteImport } from './routes/_admin.guide-images'
import { Route as AdminFaqRouteImport } from './routes/_admin.faq'
import { Route as AdminDomainMappingRouteImport } from './routes/_admin.domain-mapping'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminCustomerServiceRouteImport } from './routes/_admin.customer-service'
import { Route as AdminChatQuickRepliesRouteImport } from './routes/_admin.chat-quick-replies'
import { Route as AdminChatLogsRouteImport } from './routes/_admin.chat-logs'
import { Route as AdminCategoriesRouteImport } from './routes/_admin.categories'
import { Route as AdminAuditLogsRouteImport } from './routes/_admin.audit-logs'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin.analytics'
import { Route as AdminAiSourceRouterRouteImport } from './routes/_admin.ai-source-router'
import { Route as AdminAiResponseQualityRouteImport } from './routes/_admin.ai-response-quality'
import { Route as AdminAiReliabilityRouteImport } from './routes/_admin.ai-reliability'
import { Route as AdminAiQaRouteImport } from './routes/_admin.ai-qa'
import { Route as AdminAiPromptManagerRouteImport } from './routes/_admin.ai-prompt-manager'
import { Route as AdminAiKnowledgeImportRouteImport } from './routes/_admin.ai-knowledge-import'
import { Route as AdminAiKnowledgeRouteImport } from './routes/_admin.ai-knowledge'
import { Route as AdminAiDiagnosticsRouteImport } from './routes/_admin.ai-diagnostics'
import { Route as AdminAiContentStudioRouteImport } from './routes/_admin.ai-content-studio'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin-users'
import { Route as AdminActionButtonsRouteImport } from './routes/_admin.action-buttons'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnmatchedQuestionsRoute = AdminUnmatchedQuestionsRouteImport.update({
  id: '/unmatched-questions',
  path: '/unmatched-questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemeSettingsRoute = AdminThemeSettingsRouteImport.update({
  id: '/theme-settings',
  path: '/theme-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteContentRoute = AdminSiteContentRouteImport.update({
  id: '/site-content',
  path: '/site-content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityPermissionsRoute =
  AdminSecurityPermissionsRouteImport.update({
    id: '/security-permissions',
    path: '/security-permissions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPromptHistoryRoute = AdminPromptHistoryRouteImport.update({
  id: '/prompt-history',
  path: '/prompt-history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformTransferRoute = AdminPlatformTransferRouteImport.update({
  id: '/platform-transfer',
  path: '/platform-transfer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformControlCenterRoute =
  AdminPlatformControlCenterRouteImport.update({
    id: '/platform-control-center',
    path: '/platform-control-center',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminLocaleStudioRoute = AdminLocaleStudioRouteImport.update({
  id: '/locale-studio',
  path: '/locale-studio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpCardsRoute = AdminHelpCardsRouteImport.update({
  id: '/help-cards',
  path: '/help-cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuideImagesRoute = AdminGuideImagesRouteImport.update({
  id: '/guide-images',
  path: '/guide-images',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDomainMappingRoute = AdminDomainMappingRouteImport.update({
  id: '/domain-mapping',
  path: '/domain-mapping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerServiceRoute = AdminCustomerServiceRouteImport.update({
  id: '/customer-service',
  path: '/customer-service',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatQuickRepliesRoute = AdminChatQuickRepliesRouteImport.update({
  id: '/chat-quick-replies',
  path: '/chat-quick-replies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatLogsRoute = AdminChatLogsRouteImport.update({
  id: '/chat-logs',
  path: '/chat-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiSourceRouterRoute = AdminAiSourceRouterRouteImport.update({
  id: '/ai-source-router',
  path: '/ai-source-router',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiResponseQualityRoute = AdminAiResponseQualityRouteImport.update({
  id: '/ai-response-quality',
  path: '/ai-response-quality',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiReliabilityRoute = AdminAiReliabilityRouteImport.update({
  id: '/ai-reliability',
  path: '/ai-reliability',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiQaRoute = AdminAiQaRouteImport.update({
  id: '/ai-qa',
  path: '/ai-qa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiPromptManagerRoute = AdminAiPromptManagerRouteImport.update({
  id: '/ai-prompt-manager',
  path: '/ai-prompt-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiKnowledgeImportRoute = AdminAiKnowledgeImportRouteImport.update({
  id: '/ai-knowledge-import',
  path: '/ai-knowledge-import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiKnowledgeRoute = AdminAiKnowledgeRouteImport.update({
  id: '/ai-knowledge',
  path: '/ai-knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiDiagnosticsRoute = AdminAiDiagnosticsRouteImport.update({
  id: '/ai-diagnostics',
  path: '/ai-diagnostics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiContentStudioRoute = AdminAiContentStudioRouteImport.update({
  id: '/ai-content-studio',
  path: '/ai-content-studio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActionButtonsRoute = AdminActionButtonsRouteImport.update({
  id: '/action-buttons',
  path: '/action-buttons',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/action-buttons': typeof AdminActionButtonsRoute
  '/admin-users': typeof AdminAdminUsersRoute
  '/ai-content-studio': typeof AdminAiContentStudioRoute
  '/ai-diagnostics': typeof AdminAiDiagnosticsRoute
  '/ai-knowledge': typeof AdminAiKnowledgeRoute
  '/ai-knowledge-import': typeof AdminAiKnowledgeImportRoute
  '/ai-prompt-manager': typeof AdminAiPromptManagerRoute
  '/ai-qa': typeof AdminAiQaRoute
  '/ai-reliability': typeof AdminAiReliabilityRoute
  '/ai-response-quality': typeof AdminAiResponseQualityRoute
  '/ai-source-router': typeof AdminAiSourceRouterRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/audit-logs': typeof AdminAuditLogsRoute
  '/categories': typeof AdminCategoriesRoute
  '/chat-logs': typeof AdminChatLogsRoute
  '/chat-quick-replies': typeof AdminChatQuickRepliesRoute
  '/customer-service': typeof AdminCustomerServiceRoute
  '/dashboard': typeof AdminDashboardRoute
  '/domain-mapping': typeof AdminDomainMappingRoute
  '/faq': typeof AdminFaqRoute
  '/guide-images': typeof AdminGuideImagesRoute
  '/help-cards': typeof AdminHelpCardsRoute
  '/locale-studio': typeof AdminLocaleStudioRoute
  '/platform-control-center': typeof AdminPlatformControlCenterRoute
  '/platform-transfer': typeof AdminPlatformTransferRoute
  '/prompt-history': typeof AdminPromptHistoryRoute
  '/security-permissions': typeof AdminSecurityPermissionsRoute
  '/site-content': typeof AdminSiteContentRoute
  '/theme-settings': typeof AdminThemeSettingsRoute
  '/unmatched-questions': typeof AdminUnmatchedQuestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/action-buttons': typeof AdminActionButtonsRoute
  '/admin-users': typeof AdminAdminUsersRoute
  '/ai-content-studio': typeof AdminAiContentStudioRoute
  '/ai-diagnostics': typeof AdminAiDiagnosticsRoute
  '/ai-knowledge': typeof AdminAiKnowledgeRoute
  '/ai-knowledge-import': typeof AdminAiKnowledgeImportRoute
  '/ai-prompt-manager': typeof AdminAiPromptManagerRoute
  '/ai-qa': typeof AdminAiQaRoute
  '/ai-reliability': typeof AdminAiReliabilityRoute
  '/ai-response-quality': typeof AdminAiResponseQualityRoute
  '/ai-source-router': typeof AdminAiSourceRouterRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/audit-logs': typeof AdminAuditLogsRoute
  '/categories': typeof AdminCategoriesRoute
  '/chat-logs': typeof AdminChatLogsRoute
  '/chat-quick-replies': typeof AdminChatQuickRepliesRoute
  '/customer-service': typeof AdminCustomerServiceRoute
  '/dashboard': typeof AdminDashboardRoute
  '/domain-mapping': typeof AdminDomainMappingRoute
  '/faq': typeof AdminFaqRoute
  '/guide-images': typeof AdminGuideImagesRoute
  '/help-cards': typeof AdminHelpCardsRoute
  '/locale-studio': typeof AdminLocaleStudioRoute
  '/platform-control-center': typeof AdminPlatformControlCenterRoute
  '/platform-transfer': typeof AdminPlatformTransferRoute
  '/prompt-history': typeof AdminPromptHistoryRoute
  '/security-permissions': typeof AdminSecurityPermissionsRoute
  '/site-content': typeof AdminSiteContentRoute
  '/theme-settings': typeof AdminThemeSettingsRoute
  '/unmatched-questions': typeof AdminUnmatchedQuestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/action-buttons': typeof AdminActionButtonsRoute
  '/_admin/admin-users': typeof AdminAdminUsersRoute
  '/_admin/ai-content-studio': typeof AdminAiContentStudioRoute
  '/_admin/ai-diagnostics': typeof AdminAiDiagnosticsRoute
  '/_admin/ai-knowledge': typeof AdminAiKnowledgeRoute
  '/_admin/ai-knowledge-import': typeof AdminAiKnowledgeImportRoute
  '/_admin/ai-prompt-manager': typeof AdminAiPromptManagerRoute
  '/_admin/ai-qa': typeof AdminAiQaRoute
  '/_admin/ai-reliability': typeof AdminAiReliabilityRoute
  '/_admin/ai-response-quality': typeof AdminAiResponseQualityRoute
  '/_admin/ai-source-router': typeof AdminAiSourceRouterRoute
  '/_admin/analytics': typeof AdminAnalyticsRoute
  '/_admin/audit-logs': typeof AdminAuditLogsRoute
  '/_admin/categories': typeof AdminCategoriesRoute
  '/_admin/chat-logs': typeof AdminChatLogsRoute
  '/_admin/chat-quick-replies': typeof AdminChatQuickRepliesRoute
  '/_admin/customer-service': typeof AdminCustomerServiceRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/domain-mapping': typeof AdminDomainMappingRoute
  '/_admin/faq': typeof AdminFaqRoute
  '/_admin/guide-images': typeof AdminGuideImagesRoute
  '/_admin/help-cards': typeof AdminHelpCardsRoute
  '/_admin/locale-studio': typeof AdminLocaleStudioRoute
  '/_admin/platform-control-center': typeof AdminPlatformControlCenterRoute
  '/_admin/platform-transfer': typeof AdminPlatformTransferRoute
  '/_admin/prompt-history': typeof AdminPromptHistoryRoute
  '/_admin/security-permissions': typeof AdminSecurityPermissionsRoute
  '/_admin/site-content': typeof AdminSiteContentRoute
  '/_admin/theme-settings': typeof AdminThemeSettingsRoute
  '/_admin/unmatched-questions': typeof AdminUnmatchedQuestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/action-buttons'
    | '/admin-users'
    | '/ai-content-studio'
    | '/ai-diagnostics'
    | '/ai-knowledge'
    | '/ai-knowledge-import'
    | '/ai-prompt-manager'
    | '/ai-qa'
    | '/ai-reliability'
    | '/ai-response-quality'
    | '/ai-source-router'
    | '/analytics'
    | '/audit-logs'
    | '/categories'
    | '/chat-logs'
    | '/chat-quick-replies'
    | '/customer-service'
    | '/dashboard'
    | '/domain-mapping'
    | '/faq'
    | '/guide-images'
    | '/help-cards'
    | '/locale-studio'
    | '/platform-control-center'
    | '/platform-transfer'
    | '/prompt-history'
    | '/security-permissions'
    | '/site-content'
    | '/theme-settings'
    | '/unmatched-questions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/action-buttons'
    | '/admin-users'
    | '/ai-content-studio'
    | '/ai-diagnostics'
    | '/ai-knowledge'
    | '/ai-knowledge-import'
    | '/ai-prompt-manager'
    | '/ai-qa'
    | '/ai-reliability'
    | '/ai-response-quality'
    | '/ai-source-router'
    | '/analytics'
    | '/audit-logs'
    | '/categories'
    | '/chat-logs'
    | '/chat-quick-replies'
    | '/customer-service'
    | '/dashboard'
    | '/domain-mapping'
    | '/faq'
    | '/guide-images'
    | '/help-cards'
    | '/locale-studio'
    | '/platform-control-center'
    | '/platform-transfer'
    | '/prompt-history'
    | '/security-permissions'
    | '/site-content'
    | '/theme-settings'
    | '/unmatched-questions'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/action-buttons'
    | '/_admin/admin-users'
    | '/_admin/ai-content-studio'
    | '/_admin/ai-diagnostics'
    | '/_admin/ai-knowledge'
    | '/_admin/ai-knowledge-import'
    | '/_admin/ai-prompt-manager'
    | '/_admin/ai-qa'
    | '/_admin/ai-reliability'
    | '/_admin/ai-response-quality'
    | '/_admin/ai-source-router'
    | '/_admin/analytics'
    | '/_admin/audit-logs'
    | '/_admin/categories'
    | '/_admin/chat-logs'
    | '/_admin/chat-quick-replies'
    | '/_admin/customer-service'
    | '/_admin/dashboard'
    | '/_admin/domain-mapping'
    | '/_admin/faq'
    | '/_admin/guide-images'
    | '/_admin/help-cards'
    | '/_admin/locale-studio'
    | '/_admin/platform-control-center'
    | '/_admin/platform-transfer'
    | '/_admin/prompt-history'
    | '/_admin/security-permissions'
    | '/_admin/site-content'
    | '/_admin/theme-settings'
    | '/_admin/unmatched-questions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/unmatched-questions': {
      id: '/_admin/unmatched-questions'
      path: '/unmatched-questions'
      fullPath: '/unmatched-questions'
      preLoaderRoute: typeof AdminUnmatchedQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/theme-settings': {
      id: '/_admin/theme-settings'
      path: '/theme-settings'
      fullPath: '/theme-settings'
      preLoaderRoute: typeof AdminThemeSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/site-content': {
      id: '/_admin/site-content'
      path: '/site-content'
      fullPath: '/site-content'
      preLoaderRoute: typeof AdminSiteContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/security-permissions': {
      id: '/_admin/security-permissions'
      path: '/security-permissions'
      fullPath: '/security-permissions'
      preLoaderRoute: typeof AdminSecurityPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/prompt-history': {
      id: '/_admin/prompt-history'
      path: '/prompt-history'
      fullPath: '/prompt-history'
      preLoaderRoute: typeof AdminPromptHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/platform-transfer': {
      id: '/_admin/platform-transfer'
      path: '/platform-transfer'
      fullPath: '/platform-transfer'
      preLoaderRoute: typeof AdminPlatformTransferRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/platform-control-center': {
      id: '/_admin/platform-control-center'
      path: '/platform-control-center'
      fullPath: '/platform-control-center'
      preLoaderRoute: typeof AdminPlatformControlCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/locale-studio': {
      id: '/_admin/locale-studio'
      path: '/locale-studio'
      fullPath: '/locale-studio'
      preLoaderRoute: typeof AdminLocaleStudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/help-cards': {
      id: '/_admin/help-cards'
      path: '/help-cards'
      fullPath: '/help-cards'
      preLoaderRoute: typeof AdminHelpCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/guide-images': {
      id: '/_admin/guide-images'
      path: '/guide-images'
      fullPath: '/guide-images'
      preLoaderRoute: typeof AdminGuideImagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/faq': {
      id: '/_admin/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/domain-mapping': {
      id: '/_admin/domain-mapping'
      path: '/domain-mapping'
      fullPath: '/domain-mapping'
      preLoaderRoute: typeof AdminDomainMappingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customer-service': {
      id: '/_admin/customer-service'
      path: '/customer-service'
      fullPath: '/customer-service'
      preLoaderRoute: typeof AdminCustomerServiceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/chat-quick-replies': {
      id: '/_admin/chat-quick-replies'
      path: '/chat-quick-replies'
      fullPath: '/chat-quick-replies'
      preLoaderRoute: typeof AdminChatQuickRepliesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/chat-logs': {
      id: '/_admin/chat-logs'
      path: '/chat-logs'
      fullPath: '/chat-logs'
      preLoaderRoute: typeof AdminChatLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/categories': {
      id: '/_admin/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/audit-logs': {
      id: '/_admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-source-router': {
      id: '/_admin/ai-source-router'
      path: '/ai-source-router'
      fullPath: '/ai-source-router'
      preLoaderRoute: typeof AdminAiSourceRouterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-response-quality': {
      id: '/_admin/ai-response-quality'
      path: '/ai-response-quality'
      fullPath: '/ai-response-quality'
      preLoaderRoute: typeof AdminAiResponseQualityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-reliability': {
      id: '/_admin/ai-reliability'
      path: '/ai-reliability'
      fullPath: '/ai-reliability'
      preLoaderRoute: typeof AdminAiReliabilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-qa': {
      id: '/_admin/ai-qa'
      path: '/ai-qa'
      fullPath: '/ai-qa'
      preLoaderRoute: typeof AdminAiQaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-prompt-manager': {
      id: '/_admin/ai-prompt-manager'
      path: '/ai-prompt-manager'
      fullPath: '/ai-prompt-manager'
      preLoaderRoute: typeof AdminAiPromptManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-knowledge-import': {
      id: '/_admin/ai-knowledge-import'
      path: '/ai-knowledge-import'
      fullPath: '/ai-knowledge-import'
      preLoaderRoute: typeof AdminAiKnowledgeImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-knowledge': {
      id: '/_admin/ai-knowledge'
      path: '/ai-knowledge'
      fullPath: '/ai-knowledge'
      preLoaderRoute: typeof AdminAiKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-diagnostics': {
      id: '/_admin/ai-diagnostics'
      path: '/ai-diagnostics'
      fullPath: '/ai-diagnostics'
      preLoaderRoute: typeof AdminAiDiagnosticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-content-studio': {
      id: '/_admin/ai-content-studio'
      path: '/ai-content-studio'
      fullPath: '/ai-content-studio'
      preLoaderRoute: typeof AdminAiContentStudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin-users': {
      id: '/_admin/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/action-buttons': {
      id: '/_admin/action-buttons'
      path: '/action-buttons'
      fullPath: '/action-buttons'
      preLoaderRoute: typeof AdminActionButtonsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActionButtonsRoute: typeof AdminActionButtonsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAiContentStudioRoute: typeof AdminAiContentStudioRoute
  AdminAiDiagnosticsRoute: typeof AdminAiDiagnosticsRoute
  AdminAiKnowledgeRoute: typeof AdminAiKnowledgeRoute
  AdminAiKnowledgeImportRoute: typeof AdminAiKnowledgeImportRoute
  AdminAiPromptManagerRoute: typeof AdminAiPromptManagerRoute
  AdminAiQaRoute: typeof AdminAiQaRoute
  AdminAiReliabilityRoute: typeof AdminAiReliabilityRoute
  AdminAiResponseQualityRoute: typeof AdminAiResponseQualityRoute
  AdminAiSourceRouterRoute: typeof AdminAiSourceRouterRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminChatLogsRoute: typeof AdminChatLogsRoute
  AdminChatQuickRepliesRoute: typeof AdminChatQuickRepliesRoute
  AdminCustomerServiceRoute: typeof AdminCustomerServiceRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDomainMappingRoute: typeof AdminDomainMappingRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminGuideImagesRoute: typeof AdminGuideImagesRoute
  AdminHelpCardsRoute: typeof AdminHelpCardsRoute
  AdminLocaleStudioRoute: typeof AdminLocaleStudioRoute
  AdminPlatformControlCenterRoute: typeof AdminPlatformControlCenterRoute
  AdminPlatformTransferRoute: typeof AdminPlatformTransferRoute
  AdminPromptHistoryRoute: typeof AdminPromptHistoryRoute
  AdminSecurityPermissionsRoute: typeof AdminSecurityPermissionsRoute
  AdminSiteContentRoute: typeof AdminSiteContentRoute
  AdminThemeSettingsRoute: typeof AdminThemeSettingsRoute
  AdminUnmatchedQuestionsRoute: typeof AdminUnmatchedQuestionsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActionButtonsRoute: AdminActionButtonsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAiContentStudioRoute: AdminAiContentStudioRoute,
  AdminAiDiagnosticsRoute: AdminAiDiagnosticsRoute,
  AdminAiKnowledgeRoute: AdminAiKnowledgeRoute,
  AdminAiKnowledgeImportRoute: AdminAiKnowledgeImportRoute,
  AdminAiPromptManagerRoute: AdminAiPromptManagerRoute,
  AdminAiQaRoute: AdminAiQaRoute,
  AdminAiReliabilityRoute: AdminAiReliabilityRoute,
  AdminAiResponseQualityRoute: AdminAiResponseQualityRoute,
  AdminAiSourceRouterRoute: AdminAiSourceRouterRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminChatLogsRoute: AdminChatLogsRoute,
  AdminChatQuickRepliesRoute: AdminChatQuickRepliesRoute,
  AdminCustomerServiceRoute: AdminCustomerServiceRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDomainMappingRoute: AdminDomainMappingRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminGuideImagesRoute: AdminGuideImagesRoute,
  AdminHelpCardsRoute: AdminHelpCardsRoute,
  AdminLocaleStudioRoute: AdminLocaleStudioRoute,
  AdminPlatformControlCenterRoute: AdminPlatformControlCenterRoute,
  AdminPlatformTransferRoute: AdminPlatformTransferRoute,
  AdminPromptHistoryRoute: AdminPromptHistoryRoute,
  AdminSecurityPermissionsRoute: AdminSecurityPermissionsRoute,
  AdminSiteContentRoute: AdminSiteContentRoute,
  AdminThemeSettingsRoute: AdminThemeSettingsRoute,
  AdminUnmatchedQuestionsRoute: AdminUnmatchedQuestionsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
