import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "../..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const checks = [];
const expect = (name, condition) => checks.push({ name, ok: Boolean(condition) });

const core = read("backend-api/src/core.js");
const server = read("backend-api/src/server.js");
const env = read("backend-api/src/env.js");
const adminLayout = read("admin-pro/src/components/AdminLayout.tsx");
const domainPage = read("admin-pro/src/routes/_admin.domain-mapping.tsx");
const guidePage = read("admin-pro/src/routes/_admin.guide-images.tsx");
const adminApi = read("admin-pro/src/lib/api.ts");
const guidePublicPage = read("guide-pro/src/routes/_public.guides.$slug.tsx");
const guidePublicApi = read("guide-pro/src/lib/api.ts");
const r2Adapter = read("backend-api/src/r2-adapter.js");
const publishingMigration = read("backend-api/migrations/031_v1.14.3_guide_publishing_state_repair_platform_self_service_upload.sql");
const migration = read("backend-api/migrations/032_v1.15.0_advanced_visual_guide_studio_motion_media.sql");
const stabilizationMigration = read("backend-api/migrations/033_v1.15.1_stabilization_security_repair.sql");
const reliabilityMigration = read("backend-api/migrations/034_v1.15.2_ai_response_reliability_repair.sql");
const promptFirstMigration = read("backend-api/migrations/035_v1.15.3_prompt_first_ai_repair.sql");
const promptRuntimeMigration = read("backend-api/migrations/036_v1.15.4_prompt_runtime_versioning_repair.sql");
const simplifiedAiMigration = read("backend-api/migrations/037_v1.15.5_simplified_ai_production_runtime.sql");
const promptRuntimeModule = read("backend-api/src/prompt-runtime.js");
const promptManagerPage = read("admin-pro/src/routes/_admin.ai-prompt-manager.tsx");
const menuImagesPage = read("admin-pro/src/routes/_admin.ai-content-studio.tsx");
const diagnosticsPage = read("admin-pro/src/routes/_admin.ai-diagnostics.tsx");
const chatLogsPage = read("admin-pro/src/routes/_admin.chat-logs.tsx");
const migrationRunner = read("backend-api/src/migration-files.js");
const networkSafety = read("backend-api/src/network-safety.js");
const richHtml = read("backend-api/src/rich-html.js");
const guideSanitizer = read("guide-pro/src/lib/sanitize-html.ts");
const guideHeaders = read("guide-pro/public/_headers");
const chatHeaders = read("chat-pro/public/_headers");
const adminHeaders = read("admin-pro/public/_headers");
const integrationTest = read("backend-api/scripts/integration-test.js");
const chatApp = read("chat-pro/src/App.tsx");
const chatConfig = read("chat-pro/src/lib/chat-config.ts");
const plainTextAi = read("backend-api/src/plain-text-ai.js");

expect("Backend and server retain the SSE delivery runtime on the current release", core.includes("1.18.1-ai-knowledge-runtime") && server.includes("1.18.1-ai-knowledge-runtime"));
expect("Domain route IDs are extracted from the numeric path segment", core.includes("function domainIdFromPath") && core.includes("Number.isSafeInteger(id)") && core.includes("DOMAIN_ID_INVALID"));
expect("Provision uses the validated domain ID", core.includes("provisionMappedDomain(env, domainIdFromPath(path), scope)") && !core.includes("provisionMappedDomain(env, idFromParts(path, 3), scope)"));
expect("Sync, verify, and delete use the validated domain ID", ["syncMappedDomain(env, domainIdFromPath(path), scope)", "verifyMappedDomain(env, domainIdFromPath(path), scope)", "deleteMappedDomain(env, domainIdFromPath(path), scope)"].every((item) => core.includes(item)));
expect("Invalid domain IDs return a client error before SQL", core.includes("DOMAIN_ID_INVALID") && core.includes("The domain mapping ID is invalid."));
expect("Cloudflare configuration status is safe and non-secret", core.includes("function cloudflareConfigurationStatus") && core.includes("required_env") && core.includes("missing_env") && !core.includes("api_token: config.api_token"));
expect("Cloudflare provisioning has a clear 503 guard", core.includes("CLOUDFLARE_NOT_CONFIGURED") && core.includes("Missing Render variables") && core.includes("503"));
expect("Domain mapping exposes missing configuration names", core.includes("const cloudflare = { ...cloudflareConfigurationStatus(env)") && core.includes("cloudflare.missing_env.join"));
expect("Render environment validation covers Cloudflare prerequisites", env.includes("CLOUDFLARE_CUSTOM_HOSTNAMES_ENABLED") && env.includes("CLOUDFLARE_API_TOKEN") && env.includes("CLOUDFLARE_ZONE_ID") && env.includes("CLOUDFLARE_SAAS_CNAME_TARGET"));
expect("Admin disables Provision until Cloudflare is configured", domainPage.includes("const cloudflareReady = data?.cloudflare?.configured === true") && domainPage.includes("disabled={!cloudflareReady}"));
expect("Admin displays the exact missing Render variables", domainPage.includes("data?.cloudflare?.missing_env") && domainPage.includes("Configure these Render variables only when you need client-owned custom domains"));
expect("Admin release marker is v1.18.0", adminLayout.includes('const ADMIN_VERSION = "v1.18.1"'));
expect("v1.14.1 single-image contract remains present", core.includes("const legacyContentImages = imageDelivery.image_count ? [] : contentImages") && core.includes("A response without procedural steps has one canonical visual at most"));
expect("Platform context remains strict with no fallback", core.includes("PLATFORM_CONTEXT_REQUIRED") && core.includes("fallback_applied: false") && !core.includes("publicReference || 'default'"));
expect("v1.14.3 migration repairs existing parent Guide drafts", publishingMigration.includes("UPDATE guides g") && publishingMigration.includes("gt.status = 'published'"));
expect("Guide publish activates the translation and parent atomically", core.includes("WITH published AS (") && core.includes("UPDATE guides g SET status='published'"));
expect("Batch publish activates every affected parent Guide", core.includes("guides_activated") && core.includes("SELECT DISTINCT guide_id FROM published"));
expect("Guide reads expose derived publication state", core.includes("publication_status") && core.includes("published_locale_count") && core.includes("enabled_locale_count"));
expect("A draft default-locale translation cannot leak through the legacy parent row", core.includes("const hasLocaleRow") && core.includes("if (!hasLocaleRow)") && core.includes("GUIDE_TRANSLATION_UNAVAILABLE"));
expect("Saving legacy Guide fields cannot silently demote a published locale", core.includes("cover_image_url=EXCLUDED.cover_image_url,keywords=EXCLUDED.keywords,updated_at=NOW()"));
expect("Guide owner permissions are enforced by the backend", core.includes("GUIDE_UPLOAD_DENIED") && core.includes("GUIDE_PUBLISH_DENIED") && core.includes("requireGuidePublish(scope)"));
expect("Guide UI reads platform upload and publish capabilities", guidePage.includes("can_upload_guides") && guidePage.includes("can_publish_guides"));
expect("Guide UI uses the dedicated self-service upload route", adminApi.includes('uploadAdminFile(file, "/admin/guide-uploads")') && guidePage.includes("api.uploadGuide(file)"));
expect("Guide media keys are tenant and platform scoped", core.includes("tenant-${Number(scope.tenant_id)}/platform-${Number(scope.platform_id)}"));
expect("Guide upload validates image signatures", core.includes("detectImageContentType") && core.includes("UPLOAD_CONTENT_SIGNATURE_MISMATCH"));
expect("Guide media ownership and audit records are durable", publishingMigration.includes("guide_media_assets") && core.includes("Guide ${mediaKind} uploaded"));
expect("v1.15.0 migration adds locale-scoped cover media and motion settings", ["cover_media_type", "cover_video_url", "video_autoplay", "motion_enabled", "title_animation", "content_animation"].every((field) => migration.includes(field)));
expect("Motion media has a dedicated platform-guarded upload route", core.includes("/admin/guide-motion-uploads") && core.includes("allowMotionMedia:true") && adminApi.includes('uploadAdminFile(file, "/admin/guide-motion-uploads")'));
expect("Guide motion uploads allow only verified GIF, MP4, and WebM media", core.includes("detectGuideMediaContentType") && core.includes("video/mp4") && core.includes("video/webm") && core.includes("String.fromCharCode(...bytes.slice(4, 8)) === 'ftyp'"));
expect("Autoplay video is normalized to muted", core.includes("const muted = autoplay ? true") && core.includes("videoAutoplay ? true"));
expect("Admin exposes cover type, autoplay, loop, poster, and safe text motion controls", ["cover_media_type", "video_autoplay", "video_loop", "cover_video_poster_url", "title_animation", "summary_animation", "content_animation"].every((field) => guidePage.includes(field)));
expect("Public Guide renders video and animated GIF-compatible images", guidePublicPage.includes("<video") && guidePublicPage.includes("coverMedia?.type === \"video\"") && guidePublicApi.includes("coverMediaType === \"video\""));
expect("Public Guide honors reduced-motion preferences", guidePublicPage.includes("prefers-reduced-motion: reduce") && guidePublicPage.includes("useReducedMotion") && guidePublicPage.includes("!prefersReducedMotion"));
expect("Only allowlisted motion presets reach the renderer", core.includes("GUIDE_ANIMATION_PRESETS") && guidePublicPage.includes("SAFE_MOTION_PRESETS"));
expect("R2 media delivery supports HTTP byte ranges", r2Adapter.includes("supportsHttpRange: true") && r2Adapter.includes("Range: range") && core.includes("'Content-Range'"));
expect("Retired AI modules are absent from navigation and blocked by backend 410", !adminLayout.includes('path: "/ai-response-quality"') && !adminLayout.includes('path: "/ai-qa"') && !adminLayout.includes('path: "/ai-source-router"') && core.includes("AI_MODULE_RETIRED") && core.includes("retiredAiAdminEndpoint(path)"));
expect("Only hard safety boundaries bypass the active Prompt Manager runtime", core.includes("localCandidate?.intent === 'boundary'") && core.includes("resolutionPath = 'local_conversation'") && core.includes("ordinary messages must flow"));
expect("Saved reliability settings drive bounded synchronous retries while the durable worker owns background retries", core.includes("attempts:background ? 1 : 1 + Number(reliability?.max_retries || 0)") && core.includes("deadline_at:deadlineAt") && core.includes("payload.background_job === true ? 0 : turnStarted + 20000"));
expect("Simplified runtime always answers through one prompt-first provider stage", core.includes("async function promptFirstAiResponse") && core.includes("prompt_first_grounded_answer") && core.includes("prompt_first_general_answer") && core.includes("promptFirstMode = !local") && core.includes("assistant-profile-menu-image-one-call-v1"));
expect("Prompt-first answers attach only server-selected validated source assets", core.includes("rankApprovedMenuCandidates(message, unified.rows, 3)") && core.includes("const assets = selected ? await approvedAssetsForContent") && core.includes("if (assets.images[0]) blocks.push"));
expect("Current DeepSeek model replaces retired defaults", env.includes("deepseek-v4-flash") && core.includes("DEEPSEEK_DEFAULT_MODEL = 'deepseek-v4-flash'") && promptFirstMigration.includes("deepseek-chat','deepseek-reasoner") && promptFirstMigration.includes("model='deepseek-v4-flash'"));
expect("Assistant Setup owns production provider and memory controls", adminApi.includes("getAiSettings") && adminApi.includes("updateAiSettings") && promptManagerPage.includes("Production AI settings") && promptManagerPage.includes("One DeepSeek call") && promptManagerPage.includes("Save production settings"));
expect("Admin reliability test calls the real provider safely", core.includes("This is a provider connectivity test") && core.includes("provider_http_status") && core.includes("API key configured"));
expect("Only approved Menu & Images are loaded into the live catalog", core.includes("async function buildPromptImageCatalog") && core.includes("source_type='prompt_image'") && core.includes("approval_status='approved'") && core.includes("status='published'"));
expect("General questions remain allowed when no approved menu matches", core.includes("general_prompt_answers_allowed:true") && plainTextAi.includes("No approved Menu & Images item matched this message. Answer from the Assistant Setup") && core.includes("require_approved_context:false"));
expect("Locale routing can use the platform default without crossing tenants", core.includes("exact_then_default") && core.includes("defaultLocale = normalizeLocale(scope.default_locale") && reliabilityMigration.includes("locale_strategy='exact_then_default'"));
expect("Customer responses never expose raw provider failures", !core.includes("provider_error: usedDeepSeek") && plainTextAi.includes("The response is taking longer than expected") && core.includes("provider_failure_retry_exhausted") && chatApp.includes("AsyncProcessingIndicator"));
expect("Chat has Indonesian, Chinese, Burmese, Hindi, and English safety copy", ["id:","zh:","my:","hi:","en:"].every((token) => chatConfig.includes(token)) && chatConfig.includes("Layanan sedang mengalami gangguan"));
expect("Diagnostics expose the simplified runtime and retired modules", core.includes("runtime_mode:'assistant_profile_menu_image'") && core.includes("retired_modules:source_router.retired_modules") && diagnosticsPage.includes("Retired AI modules"));
expect("Rich HTML is sanitized on both server and Guide client", richHtml.includes("sanitize-html") && core.includes("sanitizeRichHtml") && guideSanitizer.includes("DOMPurify.sanitize"));
expect("Pages deployments include CSP and defensive headers", [guideHeaders, chatHeaders, adminHeaders].every((value) => value.includes("Content-Security-Policy:") && value.includes("object-src 'none'") && value.includes("X-Content-Type-Options: nosniff")));
expect("Connector URLs use DNS-aware, rebinding-resistant HTTPS SSRF protection", networkSafety.includes("validatePublicHttpsUrl") && networkSafety.includes("isForbiddenNetworkAddress") && networkSafety.includes("pinned.address") && networkSafety.includes("Connector redirects are not allowed") && core.includes("fetchPublicHttpsText"));
expect("SQL migration files are checksum tracked and applied", migrationRunner.includes("schema_migration_files") && migrationRunner.includes("checksum mismatch") && core.includes("applySqlMigrationFiles(client)") && stabilizationMigration.includes("v1.15.1_stabilization_security_repair") && reliabilityMigration.includes("v1.15.2_ai_response_reliability_repair") && promptFirstMigration.includes("v1.15.3_prompt_first_ai_repair") && promptRuntimeMigration.includes("v1.15.4_prompt_runtime_versioning_repair") && simplifiedAiMigration.includes("v1.15.5_simplified_ai_production_runtime"));
expect("Prompt compiler includes every enabled section and generates deterministic hashes", promptRuntimeModule.includes("compilePromptRuntime") && promptRuntimeModule.includes("compiled_prompt_hash") && promptRuntimeModule.includes("section_hashes") && promptRuntimeModule.includes("SECTION_CLIPPED"));
expect("Prompt saves, deletes, and restores publish immutable active runtimes", ["upsertPrompt", "updatePrompt", "deletePrompt", "restorePromptVersion"].every((name) => core.includes(`async function ${name}`)) && core.includes("publishPromptRuntime") && promptRuntimeMigration.includes("ai_prompt_runtime_versions") && promptRuntimeMigration.includes("ai_prompt_runtime_state"));
expect("Prompt runtime drift and old session memory are repaired automatically", core.includes("synchronizeSessionPromptRuntime") && core.includes("prompt_runtime_changed:") && core.includes("automatic_runtime_drift_repair") && promptRuntimeMigration.includes("prompt_memory_reset_reason"));
expect("Admin AI tests always use a fresh session", core.includes("admin-test-${crypto.randomUUID()}") && core.includes("testPayload.fresh_session = true") && core.includes("jsonNoStore(finalizeChatResponse"));
expect("Prompt Manager previews the exact active runtime and compiler warnings", adminApi.includes("getPromptRuntime") && adminApi.includes("rebuildPromptRuntime") && promptManagerPage.includes("Preview exact runtime") && promptManagerPage.includes("Prompt compiler findings") && promptManagerPage.includes("compiled_prompt_hash"));
expect("Chat Logs expose prompt version, hash, sections, and memory reset", chatLogsPage.includes("Prompt runtime:") && chatLogsPage.includes("Compiled Prompt SHA-256") && chatLogsPage.includes("memory_reset_reason"));
expect("Integration tests distinguish shared Pages origins from custom hostnames", integrationTest.includes("SHARED_CHAT_ORIGIN") && integrationTest.includes("Read public FAQs through the shared Chat hostname") && integrationTest.includes("Reject a route that does not match the custom hostname") && !integrationTest.includes("SKIP_CLOUDFLARE_PLATFORM_CHECK"));
expect("Integration locale fixture uses the schema tenant-platform-locale key", integrationTest.includes("ON CONFLICT(tenant_id,platform_id,locale)") && !integrationTest.includes("ON CONFLICT(platform_id,locale)"));
expect("Admin UI exposes only the simplified production AI workflow", adminLayout.includes("Assistant Setup") && adminLayout.includes("Menu & Images") && adminLayout.includes("Test & Diagnostics") && menuImagesPage.includes("The only approved business-content source") && promptManagerPage.includes("STANDARD_SECTIONS"));

for (const check of checks) console.log(`${check.ok ? "PASS" : "FAIL"} ${check.name}`);
const failed = checks.filter((check) => !check.ok);
console.log(`\n${checks.length - failed.length}/${checks.length} v1.16.1 regression checks passed`);
if (failed.length) process.exitCode = 1;
